swagger: "2.0"
info:
  title: BooksList
  version: 1.0.0
paths:
  /api/books:
    get:
      summary: Get a list of all books
      responses:
        200:
          description: A list of books
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Book'
    post:
      summary: Add a new book
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/components/schemas/Book'
      responses:
        201:
          description: The added book
          schema:
            $ref: '#/components/schemas/Book'
        400:
          description: Invalid input data
  /api/books/{book_id}:
    get:
      summary: Get details of a specific book
      parameters:
        - in: path
          name: book_id
          required: true
          type: integer
          description: The ID of the book to retrieve.
      responses:
        200:
          description: Book details successfully retrieved.
          schema:
            $ref: '#/components/schemas/Book'
        404:
          description: Book not found.
          schema:
            properties:
              message:
                type: string
                example: Book not found.
    put:
      summary: Update details of a specific book
      parameters:
        - in: path
          name: book_id
          required: true
          type: integer
          description: The ID of the book to update
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The updated book
          schema:
            $ref: '#/components/schemas/Book'
        400:
          description: Invalid input data
        404:
          description: Book not found
    delete:
      summary: Delete a specific book
      parameters:
        - in: path
          name: book_id
          required: true
          type: integer
          description: The ID of the book to delete
      responses:
        200:
          description: Book successfully deleted
        404:
          description: Book not found

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author_id:
          type: integer
      required:
        - title
