"""A module with data of the 64 UEFA teams
ranged by power ranking of season 2022/23."""


TEAMS = {
    "Top": [
        ("Manchester City", "England", "Top"),
        ("Arsenal", "England", "Top"),
        ("Manchester United", "England", "Top"),
        ("Barcelona", "Spain", "Top"),
        ("Real Madrid", "Spain", "Top"),
        ("Napoli", "Italy", "Top"),
        ("Lazio", "Italy", "Top"),
        ("Inter", "Italy", "Top"),
        ("PSG", "France", "Top"),
        ("Lens", "France", "Top"),
        ("Bayern Munich", "Germany", "Top"),
        ("Borussia Dortmund", "Germany", "Top"),
        ("Zenit", "Russia", "Top"),
        ("CSKA", "Russia", "Top"),
        ("Feyenoord", "Netherlands", "Top"),
        ("PSV", "Netherlands", "Top"),
    ],
    "Normal": [
        ("Newcastle United", "England", "Normal"),
        ("Liverpool", "England", "Normal"),
        ("Brighton & Hove Albion", "England", "Normal"),
        ("Aston Villa", "England", "Normal"),
        ("Atletico Madrid", "Spain", "Normal"),
        ("Real Sociedad", "Spain", "Normal"),
        ("Villarreal", "Spain", "Normal"),
        ("Real Betis", "Spain", "Normal"),
        ("Osasuna", "Spain", "Normal"),
        ("AC Milan", "Italy", "Normal"),
        ("Atalanta", "Italy", "Normal"),
        ("Roma", "Italy", "Normal"),
        ("Juventus", "Italy", "Normal"),
        ("Marseille", "France", "Normal"),
        ("Rennes", "France", "Normal"),
        ("Lille", "France", "Normal"),
        ("Monaco", "France", "Normal"),
        ("Lyon", "France", "Normal"),
        ("RB Leipzig", "Germany", "Normal"),
        ("Union Berlin", "Germany", "Normal"),
        ("SC Freiburg", "Germany", "Normal"),
        ("Bayer Leverkusen", "Germany", "Normal"),
        ("Eintracht Frankfurt", "Germany", "Normal"),
        ("Spartak Moscow", "Russia", "Normal"),
        ("Rostov", "Russia", "Normal"),
        ("Akhmat Grozny", "Russia", "Normal"),
        ("Krasnodar", "Russia", "Normal"),
        ("Orenburg", "Russia", "Normal"),
        ("AFC Ajax", "Netherlands", "Normal"),
        ("AZ Alkmaar", "Netherlands", "Normal"),
        ("FC Twente", "Netherlands", "Normal"),
        ("Sparta Rotterdam", "Netherlands", "Normal"),
    ],
    "Weak": [
        ("Tottenham Hotspur", "England", "Weak"),
        ("Brentford", "England", "Weak"),
        ("Chelsea", "England", "Weak"),
        ("Athletic Bilbao", "Spain", "Weak"),
        ("Mallorca", "Spain", "Weak"),
        ("Fiorentina", "Italy", "Weak"),
        ("Bologna", "Italy", "Weak"),
        ("Clermont", "France", "Weak"),
        ("Nice", "France", "Weak"),
        ("VfL Wolfsburg", "Germany", "Weak"),
        ("Mainz 05", "Germany", "Weak"),
        ("Lokomotiv Moscow", "Russia", "Weak"),
        ("Dynamo Moscow", "Russia", "Weak"),
        ("FC Utrecht", "Netherlands", "Weak"),
        ("SC Heerenveen", "Netherlands", "Weak"),
        ("RKC Waalwijk", "Netherlands", "Weak"),
    ],
}
